var KelurahanBantul = [
  ["mulyodadi", "sidomulyo", "sumbermulyo"],
  ["BangunTapan","Banguntapan","bangunretno","jagalan","jambidan","potorono","singosaren","Tamanan","wirokerten",],
  ["bantul", "bantul", "palbapang", "ringinharjo", "sabdodadi", "trirenggo"],
  ["dlingo", "dlingo", "jatimulyo", "mangunan", "muntuk", "temuwuh", "terong"],
  ["imogiri","Girirejo","Imogiri","Karangtalun","Karangtengah","Kebonagung","Selopamioro","Sriharjo","Wukirsari",],
  ["jetis", "Canden", "Patalan", "Sumberagung", "Trimulyo"],
  ["Bangunjiwo", "Ngestiharjo", "Tamantirto", "Tirtonirmolo"],
  ["Donotirto", "Parangtritis", "Tirtohargo", "Tirtomulyo", "Tirtosari"],
  ["Guwosari", "Sendangsari", "Triwidadi"],
  ["Caturharjo", "Gilangharjo", "TriharjoWijirejo"],
  ["Srimulyo", "Sitimulyo", "Srimartani"],
  ["Bawuran", "Pleret", "Segoroyoso", "Wonokromo", "Wonolelo"],
  ["Panjangrejo", "Bangunharjo", "Srihardono"],
  ["Gadingsari", "Gadingharjo", "Murtigading", "Srigading"],
  ["Argodadi", "Argorejo", "Argosari", "Argomulyo"],
  ["Bangunharjo", "Panggungharjo", "PendowoharjoT", "imbulharjo"],
  ["Poncosari", "Trimurti"],
]
console.log(KelurahanBantul)